stages:
  - build

build_windows_exe:
  stage: build
  tags:
    - windows
  script:
    - pip install --upgrade pip
    - pip install pyinstaller
    - pip install -r requirements.txt
    - pyinstaller -F -w main.py
  artifacts:
    paths:
      - dist/*.exe
    expire_in: 30 days