stages:
  - build

build_windows_exe:
  stage: build
  tags:
    - windows
  script:
    - python -m pip install --upgrade pip
    - pip install pyinstaller
    - pip install requests
    - pyinstaller -F -w main.py
  artifacts:a
    name: "exe"
    paths:
      - dist\*.exe