stages:
  - build

build_windows_exe:
  stage: build
  tags:
    - windows
  script:
    - python -m pip install --upgrade pip
    - pip install pyinstaller
    - pip install -r requirements.txt
    # 打包单文件exe，无黑窗口加 -w，有黑窗口去掉
    - pyinstaller -F main.py
  artifacts:
    paths:
      - dist/*.exe
    expire_in: 7 day